#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
port=$(ynh_app_setting_get $app port)
db_name=$(ynh_app_setting_get $app db_name)
db_user=$db_name
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# STANDARD REMOVE
#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Remove systemd configuration" --weight=1
# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status | grep -q $app
then
	echo "Remove $app service"
	yunohost service remove $app
fi

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Remove dependancies" --time --weight=7
# Remove metapackage and its dependencies
#ynh_remove_app_dependencies
ynh_package_remove libssl1.0.0
#=================================================
# REMOVE THE MYSQL DATABASE
#=================================================
#
## Remove a database if it exists, along with the associated user
#ynh_mysql_remove_db $db_user $db_name

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Remove main directory" --time --weight=1
# Remove the app directory securely
ynh_secure_remove "$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Remove nginx configuration" --time --weight=1
# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================

# Remove the dedicated php-fpm config
#ynh_remove_fpm_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	echo "Close port $port" >&2
	yunohost firewall disallow TCP $port 2>&1
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
ynh_script_progression --message="Remove Debian Jessie sources" --time --weight=1
test -f "$source_list" && rm "$source_list"

#=================================================
# REMOVE THE CRON FILE
#=================================================

# Remove a cron file
ynh_secure_remove "/etc/cron.d/$app"

# Remove a directory securely
ynh_secure_remove "/etc/$app/"

# Remove the log files
ynh_secure_remove "/var/log/$app/"

#=================================================
# GENERIC FINALIZATION
#=================================================

#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Delete system user" --time --weight=1
# Delete a system user
ynh_system_user_delete $app
